# Generated by Django 4.2.5 on 2023-11-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_order_items_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
