# Generated by Django 4.2.5 on 2023-11-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_order_cart_items_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
